version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - ${IP}:8080:8080
    volumes:
      - ./backend:/app
  db:
    image: mysql:8.0.33
    ports:
      - "${IP}:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data-volume:/var/lib/mysql

volumes:
  data-volume: